### ISSUE TITLE
error when running "shodan data list"

### ISSUE THREAD

**Issue by SockworkOrange** [achillean/shodan-python#124]
Traceback (most recent call last):
  File "/usr/local/bin/shodan", line 11, in <module>
    load_entry_point('shodan==1.21.3', 'console_scripts', 'shodan')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/shodan/cli/data.py", line 25, in data_list
    files = api.data.list_files(dataset)
  File "/usr/local/lib/python3.7/site-packages/shodan/client.py", line 65, in list_files
    return self.parent._request('/shodan/data/{}'.format(dataset), {})
  File "/usr/local/lib/python3.7/site-packages/shodan/client.py", line 336, in _request
    raise APIError('Unable to parse JSON response')
shodan.exception.APIError: Unable to parse JSON response

**Comment by achillean** [comment]
It shouldn't error out this way but that functionality is only accessible to enterprise customers so please reach out to support@shodan.io if you're still having issues accessing the bulk data.
