### ISSUE TITLE
shodan.exception.APIError: The search request timed out or your query was invalid.

### ISSUE THREAD

**Issue by upup-cmd** [achillean/shodan-python#148]
it seems that rate-limit error? 
but, i have already set 1-5 seconds sleep each request

Traceback (most recent call last):
  File "...\venv\lib\site-packages\shodan\client.py", line 518, in search
    return self._request('/shodan/host/search', args)
  File "venv\lib\site-packages\shodan\client.py", line 352, in _request
    raise APIError(data['error'])
shodan.exception.APIError: The search request timed out or your query was invalid.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "JetBrains\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "\JetBrains\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "\JetBrains\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "\JetBrains\PyCharm 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "...", line 37, in <module>
    shodanresult = shodanSearch(...)
  File "shodanApi.py", line 31, in shodanSearch
    results = api.search(query, page)
  File "...\venv\lib\site-packages\shodan\client.py", line 521, in search
    return  self._request('/shodan/host/search', args)
  File "...venv\lib\site-packages\shodan\client.py", line 352, in _request
    raise APIError(data['error'])
shodan.exception.APIError: The search request timed out or your query was invalid.

**Comment by achillean** [comment]
Please contact support@shodan.io for these types of questions.
