### ISSUE TITLE
Unable to connect to shodan

### ISSUE THREAD

**Issue by DanMcInerney** [achillean/shodan-python#22]
Me and at least one other person are having trouble using this api recently. I use it in a tool here: https://github.com/DanMcInerney/device-pharmer

I am getting shodan results exactly as the docs for this API suggest to do it, namely: 

```
api = shodan.Shodan(API_KEY)
results = api.search(search, page=1)
```

Yet even when I use my own paid-for API key, I'm getting "Unable to connect to Shodan" errors. Any idea what's going wrong?

**Comment by achillean** [comment]
Are you running it on Kali Linux? If you are then you need to update the "requests" library it ships with using:

    easy_install -U requests

If you're not on Kali then please try running the "shodan" command-line tool to make sure it isn't some other dependency problem:

    shodan init YOUR_API_KEY
    shodan count apache

If that doesn't work then please send me your API key to jmath@shodan.io and I will investigate further. Thanks!

**Comment by achillean** [comment]
Oh and I just looked at the pharmer script: you could also be hitting the rate-limits of the API. It is recommended to not do more than 1 request/ second, if you do too many requests you will get temporarily blocked/ throttled.

**Comment by DanMcInerney** [comment]
It was the requests upgrade. Thanks.

**Comment by Hunter5711** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/shodan", line 4, in <module>
    __import__('pkg_resources').run_script('shodan==1.7.7', 'shodan')
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 765, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1536, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/shodan' not found in metadata at '/usr/local/lib/python3.6/dist-packages/shodan-1.7.7-py3.6.egg-info'
Please help  me out .

**Comment by 25thengineer** [comment]
> It was the requests upgrade. Thanks.

how did you solve the problem？by which command or after all how to get it？

**Comment by achillean** [comment]
```bash
easy_install -U requests
```

The solution was mentioned further up.

**Comment by dubey-amit** [comment]
Even after easy_install -U requests
i am facing same issue . 
OS : win10

**Comment by stephen587** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/shodan", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3251, in <module>
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3235, in _call_aside
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 583, in _build_master
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 900, in require
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'click' distribution was not found and is required by shodan

im encountering this error
