### ISSUE TITLE
Shodan --help : Error

### ISSUE THREAD

**Issue by str4n63r** [achillean/shodan-python#37]
Tried launching "shodan --help" and received below error:

root@b0x:~/Desktop/Research/shodan-python# shodan --help
Traceback (most recent call last):
  File "/usr/local/bin/shodan", line 4, in <module>
    __import__('pkg_resources').run_script('shodan==1.6.5', 'shodan')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1486, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'shodan'

**Comment by Hunter5711** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/shodan", line 4, in <module>
    __import__('pkg_resources').run_script('shodan==1.7.7', 'shodan')
  File "/usr/local/lib/python3.6/dist-packages/setuptools-28.8.0-py3.6.egg/pkg_resources/__init__.py", line 743, in run_script
  File "/usr/local/lib/python3.6/dist-packages/setuptools-28.8.0-py3.6.egg/pkg_resources/__init__.py", line 1490, in run_script
pkg_resources.ResolutionError: No script named 'shodan'


Kindly hep me out plzz
